name: Check macOS Applications Folder

on:
  workflow_dispatch:
    inputs:
      macos_version:
        description: 'The macOS version to run this thing on - e.g. 15'
        required: true
        type: string
      checksdk:
        description: 'Check SDK folder?'
        required: false
        type: string
      xcodeversion:
        description: 'Version of Xcode (Semantic versioning)'
        required: true
        type: string
      checkallsdksyea:
        description: 'detailed sdk check'
        required: false
        type: string
jobs:
  macos:
    # https://github.com/actions/runner-images/blob/main/images/macos
    runs-on: macos-${{ inputs.macos_version }}
    steps:
      - name: Set up Xcode
        uses: maxim-lobanov/setup-xcode@v1.6.0
        with:
          xcode-version: 14.3.1
      - name: dir the macOS to find the Xcode List
        run: ls /Applications | grep -e Xcode
      - name: see what version if the Xcode.app
        run: xcode-select -p
      - name: dir the SDK
        run: | 
          if [ ${{ inputs.checksdk }} = "true" ]; then
            xcrun --sdk iphoneos --show-sdk-path
          fi
      - name: "[detailed] list sdks"
        run: |
          if [ ${{ inputs.checkallsdksyea }} = "true" ]; then
            xcodebuild -showsdks
          fi
