name: Check macOS Applications Folder

on:
  workflow_dispatch:
    inputs:
      macos_version:
        description: 'The macOS version to run this thing on - e.g. 15'
        required: true
        type: string
      checksdk:
        description: 'Check SDK folder?'
        required: false
        type: string
      xcodeversion:
        description: 'Version of Xcode (Semantic versioning)'
        required: false
        type: string
jobs:
  macos:
    # https://github.com/actions/runner-images/blob/main/images/macos
    runs-on: macos-${{ inputs.macos_version }}
    steps:
      - name: dir the macOS to find the Xcode List
        run: ls /Applications | grep -e Xcode
      - name: see what version if the Xcode.app
        run: xcode-select -p
      - name: dir the SDK
        run: | 
          if [ ${{ inputs.checksdk }} = "true" ]; then
            sudo xcode-select --switch /Applications/Xcode_${{ inputs.xcodeversion }}.app/Contents/Developer
            xcrun --sdk iphoneos --show-sdk-path
          fi
