name: Upload Raw SDK
on:
  workflow_dispatch:
  push:
    paths:
      - '**/**/uploadRawSDK.yml'
jobs:
  aio:
    name: Get SDK
    runs-on: macos-13
    steps: 
      - name: Checkout code
        uses: actions/checkout@v4
      - name: move to wspace
        run: cd ${{ GITHUB.WORKSPACE }}
      - name: Set up git credentials
        run: |
          git config user.name 'github-actions[bot]'
          git config user.email 'github-actions[bot]@users.noreply.github.com'
      - name: Change dir
        run: |
          cd /Applications/Xcode_14.3.1.app/Contents/Developer/Platforms/iPhoneOS.platform/Developers/SDKs
      - name: Get the Xcode SDK list
        run: |    
          ls
          exit -1
