name: Upload Raw SDK
on:
  workflow_dispatch:
    inputs:
      xcode_version:
        description: 'The Xcode version'
        required: true
        type: string
      macos_version:
        description: 'macOS version you want to run'
        required: true
        type: string
      sdk_name:
        description: 'The name of the SDK, try running the "Check Applications" workflow (e.g. iPhoneOS16.4)'
        required: true
jobs:
  aio:
    name: Get SDK
    runs-on: macos-${{ inputs.macos_version }}
    permissions:
      contents: write
    steps: 
      - name: Checkout code
        uses: actions/checkout@v4
      - name: move to wspace
        run: cd ${{ GITHUB.WORKSPACE }}
      - name: Set up git credentials
        run: |
          git config user.name 'github-actions[bot]'
          git config user.email 'github-actions[bot]@users.noreply.github.com'
      - name: Change dir
        run: |
          cd /Applications/Xcode_${{ inputs.xcode_version }}.app/Contents/Developer/Platforms/iPhoneOS.platform/Developer/SDKs/
      - name: Copy and upload
        run: |    
          cp -R /Applications/Xcode_${{ inputs.xcode_version }}.app/Contents/Developer/Platforms/iPhoneOS.platform/Developer/SDKs/iPhoneOS.sdk ${{ GITHUB.WORKSPACE }}
          cd ${{ GITHUB.WORKSPACE }} 
          mv iPhoneOS.sdk ${{ inputs.sdk_name }}.sdk
          git add *
          git commit -m "Add ${{ inputs.sdk_name }}.sdk"
          git push
